### ISSUE TITLE
How access to method without actions.

### ISSUE THREAD

**Issue by ssheduardo** [XiaoLer/Slim-Skeleton#1]
Hi,
In the routes used:

```
$app->any('/hello/{action}[/[{args}]]', 'App\Controllers\HelloController');
```

But how uses directly the method getWord

```
$app->any('/hello/myworld[/[{args}]]', 'App\Controllers\HelloController:getWorld');
```

I'm sorry for my bad english.

**Comment by xleliu** [comment]
@ssheduardo I just organize the skeleton with Slim instead of extend any features of it.
In fact the second arguments of `any` must be callabled (https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L224),
so you can not use `:` here without extend the `any` method.

My first language is not english too :).
